module

public import Mathlib.Algebra.Module.Torsion.Pi
public import Mathlib.LinearAlgebra.FreeModule.Finite.Basic
public import Mathlib.LinearAlgebra.Isomorphisms

/-!
# Saturated determinant-relation lattices

This module contains only the integral linear algebra needed to correct the
determinant-relation quotient.  The raw lattice has one basis vector for each
block.  Kummer relations are generated by vectors of the two displayed forms
`epsilon_left - epsilon_right` and `epsilon_left + epsilon_right`.

The relation submodule is replaced by its explicit `ℤ`-saturation.  We prove
that the resulting quotient has no integral scalar torsion, and that a map to
a torsion-free `ℤ`-module which kills the raw relations also kills their
saturation.  No geometric interpretation of this quotient is made here.
-/

namespace AbelianCoverHodge.Mathlib

open Module

public section

@[expose] section

/-! ## Saturation of an integral submodule -/

variable {M N : Type*} [AddCommGroup M]

/-- An integral submodule is saturated when divisibility by a nonzero integer
can be cancelled in its membership predicate. -/
def _root_.Submodule.IsZSaturated (S : Submodule ℤ M) : Prop :=
  ∀ ⦃n : ℤ⦄, n ≠ 0 → ∀ ⦃x : M⦄, n • x ∈ S → x ∈ S

/-- The `ℤ`-saturation of `R`: an element belongs when some nonzero integral
multiple of it belongs to `R`. -/
def _root_.Submodule.zSaturation (R : Submodule ℤ M) : Submodule ℤ M where
  carrier := {x | ∃ n : ℤ, n ≠ 0 ∧ n • x ∈ R}
  zero_mem' := ⟨1, one_ne_zero, by simp⟩
  add_mem' := by
    rintro x y ⟨n, hn, hx⟩ ⟨m, hm, hy⟩
    refine ⟨n * m, mul_ne_zero hn hm, ?_⟩
    have hx' : (n * m) • x ∈ R := by
      rw [mul_comm, mul_smul]
      exact R.smul_mem m hx
    have hy' : (n * m) • y ∈ R := by
      rw [mul_smul]
      exact R.smul_mem n hy
    simpa only [smul_add] using R.add_mem hx' hy'
  smul_mem' := by
    rintro c x ⟨n, hn, hx⟩
    refine ⟨n, hn, ?_⟩
    rw [smul_comm n c x]
    exact R.smul_mem c hx

@[simp]
theorem _root_.Submodule.mem_zSaturation (R : Submodule ℤ M) (x : M) :
    x ∈ R.zSaturation ↔ ∃ n : ℤ, n ≠ 0 ∧ n • x ∈ R :=
  Iff.rfl

/-- Every relation belongs to the saturation of the relation submodule. -/
theorem _root_.Submodule.le_zSaturation (R : Submodule ℤ M) : R ≤ R.zSaturation := by
  intro x hx
  exact ⟨1, one_ne_zero, by simpa using hx⟩

/-- Saturation is monotone. -/
theorem _root_.Submodule.zSaturation_mono {R S : Submodule ℤ M} (h : R ≤ S) :
    R.zSaturation ≤ S.zSaturation := by
  rintro x ⟨n, hn, hx⟩
  exact ⟨n, hn, h hx⟩

/-- A nonzero integral multiple cannot create new membership in a saturation. -/
theorem _root_.Submodule.mem_zSaturation_of_smul_mem
    (R : Submodule ℤ M) {n : ℤ} (hn : n ≠ 0) {x : M}
    (hx : n • x ∈ R.zSaturation) : x ∈ R.zSaturation := by
  rcases hx with ⟨m, hm, hmx⟩
  refine ⟨m * n, mul_ne_zero hm hn, ?_⟩
  simpa [mul_smul] using hmx

/-- The explicit saturation is saturated. -/
theorem _root_.Submodule.isZSaturated_zSaturation (R : Submodule ℤ M) :
    R.zSaturation.IsZSaturated := by
  intro n hn x hx
  exact R.mem_zSaturation_of_smul_mem hn hx

/-- The explicit saturation is the least saturated submodule containing the
original relations. -/
theorem _root_.Submodule.zSaturation_le_of_le_of_isZSaturated
    {R S : Submodule ℤ M} (hRS : R ≤ S) (hS : S.IsZSaturated) :
    R.zSaturation ≤ S := by
  rintro x ⟨n, hn, hx⟩
  exact hS hn (hRS hx)

@[simp]
theorem _root_.Submodule.zSaturation_zSaturation (R : Submodule ℤ M) :
    R.zSaturation.zSaturation = R.zSaturation := by
  apply le_antisymm
  · exact Submodule.zSaturation_le_of_le_of_isZSaturated
      le_rfl R.isZSaturated_zSaturation
  · exact R.zSaturation.le_zSaturation

/-! ## Torsion-free quotient and maps out of a saturation -/

/-- Quotienting an integral module by the saturation of any submodule produces
a torsion-free `ℤ`-module. -/
theorem _root_.Submodule.quotient_zSaturation_isTorsionFree (R : Submodule ℤ M) :
    Module.IsTorsionFree ℤ (M ⧸ R.zSaturation) :=
  Module.IsTorsionFree.of_smul_eq_zero fun (n : ℤ)
      (q : M ⧸ R.zSaturation) hnq => by
    by_cases hn : n = 0
    · exact Or.inl hn
    · right
      obtain ⟨x, rfl⟩ := R.zSaturation.mkQ_surjective q
      rw [Submodule.mkQ_apply, ← Submodule.Quotient.mk_smul,
        Submodule.Quotient.mk_eq_zero] at hnq
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact R.mem_zSaturation_of_smul_mem hn hnq

/-- Elementwise no-torsion form of
`Submodule.quotient_zSaturation_isTorsionFree`. -/
theorem _root_.Submodule.eq_zero_of_zsmul_eq_zero_in_quotient_zSaturation
    (R : Submodule ℤ M) {n : ℤ} (hn : n ≠ 0)
    {q : M ⧸ R.zSaturation} (hq : n • q = 0) : q = 0 := by
  exact (R.quotient_zSaturation_isTorsionFree.isSMulRegular
    (IsRegular.of_ne_zero hn)).right_eq_zero_of_smul hq

variable [AddCommGroup N] [Module.IsTorsionFree ℤ N]

/-- A linear map to a torsion-free integral module which kills `R` also kills
the saturation of `R`. -/
theorem _root_.Submodule.zSaturation_le_ker (R : Submodule ℤ M)
    (f : M →ₗ[ℤ] N) (hR : R ≤ LinearMap.ker f) :
    R.zSaturation ≤ LinearMap.ker f := by
  rintro x ⟨n, hn, hnx⟩
  apply LinearMap.mem_ker.mpr
  have hzero : f (n • x) = 0 := LinearMap.mem_ker.mp (hR hnx)
  have : n • f x = 0 := by simpa using hzero
  exact (smul_eq_zero_iff_right hn).mp this

/-- Kernels of maps into torsion-free integral modules are already saturated. -/
theorem _root_.LinearMap.isZSaturated_ker (f : M →ₗ[ℤ] N) :
    (LinearMap.ker f).IsZSaturated := by
  intro n hn x hx
  exact (LinearMap.ker f).zSaturation_le_ker f le_rfl
    ⟨n, hn, hx⟩

/-! ## The finite free determinant lattice and Kummer generators -/

/-- The raw determinant lattice, with one integral exponent for every block. -/
abbrev RawDeterminantLattice (ι : Type*) := ι → ℤ

/-- The distinguished basis of the raw determinant lattice. -/
noncomputable def rawDeterminantBasis (ι : Type*) [Finite ι] :
    Basis ι ℤ (RawDeterminantLattice ι) :=
  Pi.basisFun ℤ ι

/-- Explicit witness that the raw determinant lattice is free. -/
theorem rawDeterminantLattice_free (ι : Type*) [Finite ι] :
    Module.Free ℤ (RawDeterminantLattice ι) :=
  Module.Free.of_basis (rawDeterminantBasis ι)

/-- Explicit witness that the raw determinant lattice has finite rank. -/
theorem rawDeterminantLattice_finite (ι : Type*) [Finite ι] :
    Module.Finite ℤ (RawDeterminantLattice ι) :=
  Module.Finite.of_basis (rawDeterminantBasis ι)

/-- The two relation shapes used in the Kummer presentation. -/
inductive KummerRelationKind
  | sameCharacter
  | dualCharacter
  deriving DecidableEq, Repr

/-- A relation records its two block indices and whether their determinant
characters agree or are dual. -/
structure KummerRelation (ι : Type*) where
  left : ι
  right : ι
  kind : KummerRelationKind
  deriving DecidableEq, Repr

namespace KummerRelation

def same (left right : ι) : KummerRelation ι :=
  ⟨left, right, .sameCharacter⟩

def dual (left right : ι) : KummerRelation ι :=
  ⟨left, right, .dualCharacter⟩

/-- The integral vector imposed by one Kummer relation. -/
noncomputable def vector [Finite ι] (r : KummerRelation ι) :
    RawDeterminantLattice ι :=
  match r.kind with
  | .sameCharacter =>
      rawDeterminantBasis ι r.left - rawDeterminantBasis ι r.right
  | .dualCharacter =>
      rawDeterminantBasis ι r.left + rawDeterminantBasis ι r.right

@[simp]
theorem vector_same [Finite ι] (left right : ι) :
    vector (same left right) =
      rawDeterminantBasis ι left - rawDeterminantBasis ι right :=
  rfl

@[simp]
theorem vector_dual [Finite ι] (left right : ι) :
    vector (dual left right) =
      rawDeterminantBasis ι left + rawDeterminantBasis ι right :=
  rfl

end KummerRelation

/-- The raw relation submodule generated by the supplied Kummer relations. -/
noncomputable def kummerRelationSubmodule {ι : Type*} [Finite ι]
    (relations : Set (KummerRelation ι)) :
    Submodule ℤ (RawDeterminantLattice ι) :=
  Submodule.span ℤ (KummerRelation.vector '' relations)

/-- Every listed relation vector belongs to the generated relation submodule. -/
theorem KummerRelation.vector_mem_relationSubmodule {ι : Type*} [Finite ι]
    {relations : Set (KummerRelation ι)} {r : KummerRelation ι}
    (hr : r ∈ relations) :
    r.vector ∈ kummerRelationSubmodule relations := by
  apply Submodule.subset_span
  exact ⟨r, hr, rfl⟩

/-- The corrected relation submodule is the saturation of the raw Kummer
relation submodule. -/
noncomputable def kummerSaturatedSubmodule {ι : Type*} [Finite ι]
    (relations : Set (KummerRelation ι)) :
    Submodule ℤ (RawDeterminantLattice ι) :=
  (kummerRelationSubmodule relations).zSaturation

/-- The purely algebraic corrected determinant lattice. -/
abbrev SaturatedDeterminantLattice {ι : Type*} [Finite ι]
    (relations : Set (KummerRelation ι)) :=
  RawDeterminantLattice ι ⧸ kummerSaturatedSubmodule relations

/-- The corrected determinant lattice has no integral scalar torsion. -/
theorem saturatedDeterminantLattice_isTorsionFree {ι : Type*} [Finite ι]
    (relations : Set (KummerRelation ι)) :
    Module.IsTorsionFree ℤ (SaturatedDeterminantLattice relations) :=
  (kummerRelationSubmodule relations).quotient_zSaturation_isTorsionFree

/-! ## Abstract signature maps -/

/-- An integral signature lattice, with one integer for each signature row. -/
abbrev SignatureLattice (κ : Type*) := κ → ℤ

/-- Killing every displayed generator is equivalent to killing the generated
Kummer relation submodule. -/
theorem kummerRelationSubmodule_le_ker_iff {ι κ : Type*} [Finite ι]
    (relations : Set (KummerRelation ι))
    (signature : RawDeterminantLattice ι →ₗ[ℤ] SignatureLattice κ) :
    kummerRelationSubmodule relations ≤ LinearMap.ker signature ↔
      ∀ r ∈ relations, signature r.vector = 0 := by
  constructor
  · intro h r hr
    exact LinearMap.mem_ker.mp (h (r.vector_mem_relationSubmodule hr))
  · intro h
    rw [kummerRelationSubmodule, Submodule.span_le]
    rintro _ ⟨r, hr, rfl⟩
    exact LinearMap.mem_ker.mpr (h r hr)

/-- An abstract integral signature map which kills the displayed Kummer
relations also kills their saturation.  This is the precise algebraic reason
that saturation does not change the signature image. -/
theorem kummerSaturatedSubmodule_le_signatureKernel
    {ι κ : Type*} [Finite ι]
    (relations : Set (KummerRelation ι))
    (signature : RawDeterminantLattice ι →ₗ[ℤ] SignatureLattice κ)
    (killsRelations : ∀ r ∈ relations, signature r.vector = 0) :
    kummerSaturatedSubmodule relations ≤ LinearMap.ker signature := by
  apply (kummerRelationSubmodule relations).zSaturation_le_ker signature
  exact (kummerRelationSubmodule_le_ker_iff relations signature).mpr killsRelations

/-- The signature map descended to the saturated determinant lattice. -/
noncomputable def signatureOnSaturatedDeterminantLattice
    {ι κ : Type*} [Finite ι]
    (relations : Set (KummerRelation ι))
    (signature : RawDeterminantLattice ι →ₗ[ℤ] SignatureLattice κ)
    (killsRelations : ∀ r ∈ relations, signature r.vector = 0) :
    SaturatedDeterminantLattice relations →ₗ[ℤ] SignatureLattice κ :=
  (kummerSaturatedSubmodule relations).liftQ signature
    (kummerSaturatedSubmodule_le_signatureKernel
      relations signature killsRelations)

@[simp]
theorem signatureOnSaturatedDeterminantLattice_mkQ
    {ι κ : Type*} [Finite ι]
    (relations : Set (KummerRelation ι))
    (signature : RawDeterminantLattice ι →ₗ[ℤ] SignatureLattice κ)
    (killsRelations : ∀ r ∈ relations, signature r.vector = 0)
    (x : RawDeterminantLattice ι) :
    signatureOnSaturatedDeterminantLattice relations signature killsRelations
        ((kummerSaturatedSubmodule relations).mkQ x) =
      signature x :=
  rfl

/-- First isomorphism theorem for the signature map after saturated descent. -/
noncomputable def signatureQuotientEquivRange
    {ι κ : Type*} [Finite ι]
    (relations : Set (KummerRelation ι))
    (signature : RawDeterminantLattice ι →ₗ[ℤ] SignatureLattice κ)
    (killsRelations : ∀ r ∈ relations, signature r.vector = 0) :
    (SaturatedDeterminantLattice relations ⧸
        LinearMap.ker
          (signatureOnSaturatedDeterminantLattice
            relations signature killsRelations)) ≃ₗ[ℤ]
      LinearMap.range
        (signatureOnSaturatedDeterminantLattice
          relations signature killsRelations) :=
  (signatureOnSaturatedDeterminantLattice
    relations signature killsRelations).quotKerEquivRange

end

end

end AbelianCoverHodge.Mathlib
